COOKIES_BTN = (By.ID, 'rcc-confirm-button')
BUTTON_ASK = (By.CLASS_NAME, 'Button_Button_ra12g')
FORM_TITLE = (By.CLASS_NAME, 'Order_Header_BZX0b')
NAME_INPUT = (By.XPATH, '//input[@placeholder="* Nombre"]')
LAST_NAME_INPUT = (By.XPATH, '//input[@placeholder="* Apellido"]')
ADDRESS_INPUT = (By.XPATH, '//input[@placeholder="* Dirección: a dónde llevar el scooter"]')
METRO_SELECT = (By.XPATH, '//input[@placeholder="* Estación de metro"]')
PHONE_INPUT = (By.XPATH, '//input[contains(text(),"* Teléfono")]')
NEXT_BUTTON = (By.XPATH, '//button[normalize-space()="Siguiente"]')
RENT_FORM_TITLE = (By.CSS_SELECTOR, '.Order_Header__BZXOb')
DATE_INPUT = (By.XPATH, '//input[@placeholder="* Fecha de entrega"]')
DAYS_DROPDOWN = (By.XPATH, '//div[@class="Dropdown-placeholder"]')
BLACK_CHECKBOX = (By.ID, 'black')
GREY_CHECKBOX = (By.ID, 'grey')
COMMENT_INPUT = (By.XPATH, '//input[@placeholder="Comentario"]')
